FROM elasticsearch:1.7

ADD logging.yml /usr/share/elasticsearch/config/logging.yml
ADD elasticsearch.yml /etc/elasticsearch/elasticsearch.yml

RUN /usr/share/elasticsearch/bin/plugin install mobz/elasticsearch-head




